// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFileWithDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['DownloadFileWithDialog'](arg1, arg2, arg3);
}

export function DummyPeerInfo() {
  return window['go']['main']['App']['DummyPeerInfo']();
}

export function FetchNetworkFiles() {
  return window['go']['main']['App']['FetchNetworkFiles']();
}

export function FetchPeersForFile(arg1) {
  return window['go']['main']['App']['FetchPeersForFile'](arg1);
}

export function SelectShareDirectory() {
  return window['go']['main']['App']['SelectShareDirectory']();
}

export function StartPeerLogic(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartPeerLogic'](arg1, arg2, arg3, arg4);
}

export function StopPeerLogic() {
  return window['go']['main']['App']['StopPeerLogic']();
}

export function UpdatePeerConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdatePeerConfig'](arg1, arg2, arg3, arg4);
}
