// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {protocol} from '../models';
import {netip} from '../models';
import {corepeer} from '../models';

export function DownloadFileWithDialog(arg1:string,arg2:string):Promise<string>;

export function DummyDownloadProgress():Promise<main.DownloadProgressEvent>;

export function DummyPeerInfo():Promise<protocol.PeerInfo>;

export function FetchNetworkFiles():Promise<Array<protocol.FileMeta>>;

export function FetchPeersForFile(arg1:string):Promise<Array<netip.AddrPort>>;

export function GetConnectedPeers():Promise<Array<corepeer.PeerRegistryInfo>>;

export function GetCurrentConfig():Promise<corepeer.CorePeerConfig>;

export function GetCurrentSharedFiles():Promise<Array<protocol.FileMeta>>;

export function SelectShareDirectory():Promise<string>;

export function StartPeerLogic(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function StopPeerLogic():Promise<void>;

export function UpdatePeerConfig(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;
