// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {netip} from '../models';
import {protocol} from '../models';

export function DownloadFileWithDialog(arg1:netip.AddrPort,arg2:string,arg3:string):Promise<string>;

export function DummyFileMeta():Promise<protocol.FileMeta>;

export function DummyPeerInfo():Promise<protocol.PeerInfo>;

export function FetchNetworkFiles():Promise<Array<protocol.FileMeta>>;

export function FetchPeersForFile(arg1:string):Promise<Array<netip.AddrPort>>;

export function SelectShareDirectory():Promise<string>;

export function StartPeerLogic(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function StopPeerLogic():Promise<void>;

export function UpdatePeerConfig(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;
