// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFileWithDialog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DownloadFileWithDialog'](arg1, arg2, arg3, arg4);
}

export function DummyFileMeta() {
  return window['go']['main']['App']['DummyFileMeta']();
}

export function DummyPeerInfo() {
  return window['go']['main']['App']['DummyPeerInfo']();
}

export function QueryIndexServer(arg1) {
  return window['go']['main']['App']['QueryIndexServer'](arg1);
}

export function SelectShareDirectory() {
  return window['go']['main']['App']['SelectShareDirectory']();
}

export function StartPeerLogic(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartPeerLogic'](arg1, arg2, arg3, arg4);
}
